name: Create a distribution package
on:
  push:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      BRANCHAQUAWEBNGVUE: "dfsdfds"
    steps:        
      - run: echo $BRANCHAQUAWEBNGVUE