name: Create a distribution package
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      BRANCHAQUAWEBNGVUE: "dfsdfds"
    steps:      
      - run: |
          echo ${{ github.event_name }}  
      - name: Check if push
        if: github.event_name != 'push'
        run: echo $BRANCHAQUAWEBNGVUE