name: Create a distribution package
on:
  push:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      BRANCHAQUAWEBNGVUE: "dfsdfds"
    steps:        
      - name: Check if push
        if: github.event_name != 'push'
        run: echo $BRANCHAQUAWEBNGVUE